<?php
/**
 * @package     Kirchbergerknorr_CommentCart
 * @author      Leo Friedrichs <lf@kirchbergerknorr.de>
 * @copyright   Copyright (c) 2016 kirchbergerknorr GmbH (http://www.kirchbergerknorr.de)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
    if (!window.Mage) {
        var Mage = {};
    }
    Mage.baseUrl = '<?php echo Mage::getUrl('',array('_secure'=>true)); ?>';
</script>
