<?php
/**
 * @package     Kirchbergerknorr_CommentCart
 * @author      Leo Friedrichs <lf@kirchbergerknorr.de>
 * @copyright   Copyright (c) 2016 kirchbergerknorr GmbH (http://www.kirchbergerknorr.de)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
    $helper = Mage::helper('kirchbergerknorr_commentcart');
    $comment = $helper->getComment() ? $helper->getComment() : '';
?>
<ol class="checkout-agreements">
    <li class="customer-order-comment">
        <label for="customer_order_comment"><?php echo $helper->__('Your Comment for this Order') ?></label>
        <br />
        <textarea name="customer_order_comment" id="commentcart" style="width:450px; height:50px;"><?php echo $comment; ?></textarea>
    </li>
</ol>